try {
    throw new Error('test error');
} catch (e) {
    console.error(e.message);
}


function  test(){

}


test();

test();